# Day 02 - Student Data Analysis

## Objective

Analyze student data using Pandas DataFrames.

### Topics Covered

- Python Lists
- Dictionaries
- Pandas DataFrame
- Filtering
- Statistical Analysis

In [2]:
import pandas as pd

In [3]:
data = {
    "Name": [
        "Ali", "Ahmed", "Fatima", "Ayesha", "Usman",
        "Hamza", "Hassan", "Zain", "Sara", "Noor",
        "Bilal", "Kashif", "Hina", "Maryam", "Danish",
        "Imran", "Laiba", "Saad", "Areeba", "Talha"
    ],
    "Age": [
        20, 21, 19, 22, 20,
        23, 21, 20, 19, 22,
        20, 21, 20, 19, 23,
        22, 20, 21, 19, 22
    ],
    "Course": [
        "Artificial Intelligence", "Data Science", "Cyber Security", "Artificial Intelligence", "Software Engineering.",
        "Artificial Intelligence", "Data Science", "Cyber Security", "Artificial Intelligence", "Software Engineering.",
        "Artificial Intelligence", "Data Science", "Cyber Security", "Artificial Intelligence", "Software Engineering.",
        "Artificial Intelligence", "Data Science", "Cyber Security", "Artificial Intelligence", "Software Engineering."
    ],
    "Marks": [
        88, 74, 91, 68, 82,
        77, 59, 85, 94, 71,
        80, 66, 89, 73, 64,
        92, 87, 76, 81, 69
    ]
}

In [4]:
try:
    df = pd.DataFrame(data)
except Exception as e:
    print(f"Error Creating DataFrame: {e}")

In [5]:
print("Hello, World!")

Hello, World!

In [6]:
df.head()

     Name  Age                   Course  Marks
0     Ali   20  Artificial Intelligence     88
1   Ahmed   21             Data Science     74
2  Fatima   19           Cyber Security     91
3  Ayesha   22  Artificial Intelligence     68
4   Usman   20    Software Engineering.     82

In [7]:
df

      Name  Age                   Course  Marks
0      Ali   20  Artificial Intelligence     88
1    Ahmed   21             Data Science     74
2   Fatima   19           Cyber Security     91
3   Ayesha   22  Artificial Intelligence     68
4    Usman   20    Software Engineering.     82
5    Hamza   23  Artificial Intelligence     77
6   Hassan   21             Data Science     59
7     Zain   20           Cyber Security     85
8     Sara   19  Artificial Intelligence     94
9     Noor   22    Software Engineering.     71
10   Bilal   20  Artificial Intelligence     80
11  Kashif   21             Data Science     66
12    Hina   20           Cyber Security     89
13  Maryam   19  Artificial Intelligence     73
14  Danish   23    Software Engineering.     64
15   Imran   22  Artificial Intelligence     92
16   Laiba   20             Data Science     87
17    Saad   21           Cyber Security     76
18  Areeba   19  Artificial Intelligence     81
19   Talha   22    Software Engineering.     69

In [8]:
marks_over_70 = df[df["Marks"] > 70]
print("Marks Greater than 70:")
display(marks_over_70)

Marks Greater than 70:

      Name  Age                   Course  Marks
0      Ali   20  Artificial Intelligence     88
1    Ahmed   21             Data Science     74
2   Fatima   19           Cyber Security     91
4    Usman   20    Software Engineering.     82
5    Hamza   23  Artificial Intelligence     77
7     Zain   20           Cyber Security     85
8     Sara   19  Artificial Intelligence     94
9     Noor   22    Software Engineering.     71
10   Bilal   20  Artificial Intelligence     80
12    Hina   20           Cyber Security     89
13  Maryam   19  Artificial Intelligence     73
15   Imran   22  Artificial Intelligence     92
16   Laiba   20             Data Science     87
17    Saad   21           Cyber Security     76
18  Areeba   19  Artificial Intelligence     81

In [9]:
average_marks = df["Marks"].mean()
display(f"Average of Marks : {average_marks}")

'Average of Marks : 78.3'

In [10]:
highest_marks = df["Marks"].max()
display(f"Highest Marks : {highest_marks}")

'Highest Marks : 94'

In [11]:
lowest_marks = df["Marks"].min()
display(f"Lowest Marks : {lowest_marks}")

'Lowest Marks : 59'

In [17]:
total_students = len(df) # 1st method
# total_students = df.shape[0] # 2nd method
# total_students = df.index.size # 3rd method

print(f"Total number of students: {total_students}")

Total number of students: 20